### ISSUE TITLE
0.6.0 tag is outdated. Can you make a new tag?

### ISSUE THREAD

**Issue by Raptus1** [ansible/awx-ee#117] opened 2022-05-04 10:54 UTC
It is a little bit of a strech to go from a tag that is static to latest that is too dynamic.

Current EE tag 0.6.0 is not syncable so the only alternative left is latest and that is pretty unpredictable.

Love your work BTW!

**Comment by ryanmerolle** [comment] 2022-05-06 12:46
Yes I would love 0.6.0 to be rebuilt on some sort of schedule.

I also love your work.

**Comment by rebeccahhh** [comment] 2022-05-06 17:39
Thanks y'all, we love working on this. We'll be discussing this pretty soon. We'll try to communicate the decisions of that publicly so that everyone knows what the plan in. :)

**Comment by Raptus1** [comment] 2022-05-11 08:02
Sounds very good, thanks you for the reply :D

**Comment by ryanmerolle** [comment] 2022-05-17 13:20
Is the latest tag 0.6.0?

**Comment by Raptus1** [comment] 2022-06-13 10:38
Yes:
https://github.com/ansible/awx-ee/tags

There is a "latest" build, but not really something to rely on for consitency (especially now since it's broken), hence the wish for a new tag.

**Comment by PaulVerhoeven1** [comment] 2022-06-28 07:04
@rebeccahhh is there any new news about creating a new tag?

**Comment by ryanmerolle** [comment] 2022-06-28 11:20
Last I heard from Ansible team was that the docker build and release workflow for the opensource projects was being totally reworked/fixed and was weeks if not a month or two away.

**Comment by Raptus1** [comment] 2022-06-29 06:31
Hopefully that could bring about the same tagging/release-structure as the rest of AWX where awx-operator and AWX are somewhat sync on new tags/releases.

**Comment by AndrewSav** [comment] 2022-11-29 07:33
@rebeccahhh 

>Thanks y'all, we love working on this. We'll be discussing this pretty soon. We'll try to communicate the decisions of that publicly so that everyone knows what the plan in. :)

I think by any reasonable definition for this context this time frame has now elapsed. Could we please get an update?

**Comment by melslow** [comment] 2022-12-12 13:38
I agree with @AndrewSav, not having a up-to-date and static image is somewhat problematic for us. Any update would be greatly appreciated!

**Comment by rebeccahhh** [comment] 2022-12-14 16:31
hey y'all sorry. I have moved into a slightly new role so this hasn't been on my plate as of late, _but_ I am following up and poking people :)

**Comment by relrod** [comment] 2022-12-15 21:30
This is effectively a duplicate of #125 (or vice versa, I suppose). In any case, I'm going to close it out and we can continue discussing there. @fosterseth is working on solving this!

**Closed as completed by relrod** 2022-12-15 21:30 UTC
